//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Sqldata
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCart
    {
        public int Id { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
