//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubCategory
    {
        [Required(ErrorMessage = "Subcategory ID is required")]
        [Display(Name = "Subcategory")]
        public int SubCategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        [Required(ErrorMessage = "Subcategory Name is required")]
        [Display(Name = "Subcategory Name")]
        public string SubCategoryName { get; set; }
    }
}
